// Typed schema generated by hand from 06-database-schema.sql.
// Keep in sync with the SQL or regenerate with `supabase gen types typescript`.

export type UserRole = 'super_admin' | 'lc_admin' | 'teacher' | 'student';
export type UserStatus = 'invited' | 'active' | 'suspended' | 'archived';
export type LcStatus = 'active' | 'suspended' | 'deleted';
export type LocaleCode = 'en' | 'ru' | 'uz';
export type InviteStatus = 'pending' | 'accepted' | 'expired' | 'cancelled';
export type ClassStatus = 'active' | 'archived' | 'cancelled';

export interface Database {
  public: {
    Tables: {
      learning_centers: {
        Row: {
          id: string;
          name: string;
          slug: string;
          status: LcStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          status?: LcStatus;
        };
        Update: Partial<{
          name: string;
          slug: string;
          status: LcStatus;
          updated_at: string;
        }>;
      };
      profiles: {
        Row: {
          id: string;
          phone_number: string;
          username: string;
          full_name: string | null;
          role: UserRole;
          status: UserStatus;
          learning_center_id: string | null;
          locale: LocaleCode;
          created_at: string;
        };
        Insert: {
          id: string;
          phone_number: string;
          username: string;
          full_name?: string | null;
          role: UserRole;
          status?: UserStatus;
          learning_center_id?: string | null;
          locale?: LocaleCode;
        };
        Update: Partial<{
          phone_number: string;
          username: string;
          full_name: string | null;
          role: UserRole;
          status: UserStatus;
          learning_center_id: string | null;
          locale: LocaleCode;
        }>;
      };
      classes: {
        Row: {
          id: string;
          learning_center_id: string;
          name: string;
          subject: string | null;
          level: string | null;
          schedule: string | null;
          status: ClassStatus;
          created_at: string;
        };
        Insert: {
          id?: string;
          learning_center_id: string;
          name: string;
          subject?: string | null;
          level?: string | null;
          schedule?: string | null;
          status?: ClassStatus;
        };
        Update: Partial<{
          name: string;
          subject: string | null;
          level: string | null;
          schedule: string | null;
          status: ClassStatus;
        }>;
      };
      class_teachers: {
        Row: { class_id: string; teacher_id: string };
        Insert: { class_id: string; teacher_id: string };
        Update: never;
      };
      class_students: {
        Row: { class_id: string; student_id: string; joined_at: string };
        Insert: { class_id: string; student_id: string };
        Update: never;
      };
      assignments: {
        Row: {
          id: string;
          class_id: string;
          teacher_id: string | null;
          title: string;
          description: string | null;
          due_at: string | null;
          attachment_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          class_id: string;
          teacher_id: string;
          title: string;
          description?: string | null;
          due_at?: string | null;
          attachment_url?: string | null;
        };
        Update: Partial<{
          title: string;
          description: string | null;
          due_at: string | null;
          attachment_url: string | null;
        }>;
      };
      submissions: {
        Row: {
          id: string;
          assignment_id: string;
          student_id: string;
          text_answer: string | null;
          file_url: string | null;
          submitted_at: string;
          grade: number | null;
          feedback: string | null;
          graded_at: string | null;
          graded_by: string | null;
        };
        Insert: {
          id?: string;
          assignment_id: string;
          student_id: string;
          text_answer?: string | null;
          file_url?: string | null;
        };
        Update: Partial<{
          text_answer: string | null;
          file_url: string | null;
          grade: number | null;
          feedback: string | null;
          graded_at: string | null;
          graded_by: string | null;
        }>;
      };
      invitations: {
        Row: {
          id: string;
          learning_center_id: string | null;
          phone_number: string;
          role: UserRole;
          status: InviteStatus;
          class_id: string | null;
          invited_by: string | null;
          token: string;
          expires_at: string;
          accepted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          learning_center_id?: string | null;
          phone_number: string;
          role: UserRole;
          class_id?: string | null;
          invited_by?: string | null;
          token?: string;
          expires_at?: string;
        };
        Update: Partial<{
          status: InviteStatus;
          accepted_at: string | null;
          expires_at: string;
        }>;
      };
      sms_otp_log: {
        Row: {
          id: string;
          phone_number: string;
          purpose: 'login' | 'password_reset' | 'invite' | 'verify';
          success: boolean;
          code_hash: string | null;
          ip_address: string | null;
          user_agent: string | null;
          sent_at: string;
        };
        Insert: {
          phone_number: string;
          purpose: 'login' | 'password_reset' | 'invite' | 'verify';
          success?: boolean;
          code_hash?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
        };
        Update: never;
      };
    };
    Enums: {
      user_role: UserRole;
      user_status: UserStatus;
      lc_status: LcStatus;
      locale_code: LocaleCode;
      invite_status: InviteStatus;
      class_status: ClassStatus;
    };
  };
}

export type Profile = Database['public']['Tables']['profiles']['Row'];
export type LearningCenter = Database['public']['Tables']['learning_centers']['Row'];
export type Class = Database['public']['Tables']['classes']['Row'];
export type Assignment = Database['public']['Tables']['assignments']['Row'];
export type Submission = Database['public']['Tables']['submissions']['Row'];
export type Invitation = Database['public']['Tables']['invitations']['Row'];
